In [1]:
import numpy as np 
import pandas as pd

## Departments data

In [7]:
departments = pd.read_csv('departments.csv')

departments.head()

,DepartmentKey,Address,City,County,DepartmentName,DepartmentSpecialty,DepartmentType,PostalCode,CensusTract
0,-3,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,NaN
1,-2,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,NaN
2,-1,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,NaN
3,1,1500 SW 10th ST,TOPEKA,*Unspecified,INITIAL DEPT,*Unspecified,*Unknown,66604,2.017700e+10
4,2,1979 Milky Way,VERONA,*Unspecified,EHS UM DEPT,*Unspecified,*Unknown,53593,5.502501e+10

In [13]:
departments['City'].unique() 

# TOPEKA and Topek same 
# Osage City and OSAGE CITY same 
# Manhattan and MANHATTAN same

array(['*Deleted', '*Not Applicable', '*Unspecified', 'TOPEKA', 'VERONA',
       'Topeka', nan, 'CARBONDALE', 'Alma', 'Emporia', 'EMPORIA',
       'Lawrence', 'Lebo', 'LEBO', 'Meriden', 'Osage City', 'OSAGE CITY',
       'Oskaloosa', 'Rossville', 'Wamego', 'Manhattan', 'MANHATTAN',
       'LYNDON', 'Lyndon', 'Verona', 'JUNCTION CITY', 'OLATHE', 'ALMA',
       'LAWRENCE', 'MERIDEN', 'OSKALOOSA', 'ROSSVILLE', 'WAMEGO',
       'Madison', 'MONONA', 'Stoughton', 'HIAWATHA', 'HARTFORD',
       'Hiawatha', 'ESKRIDGE', 'Topek', 'Onaga', 'EDEN PRAIRIE', 'Holton',
       'ELMWOOD PARK', 'COUNCIL GROVE', 'SENECA', 'WESTMORELAND',
       'SABETHA', 'LAFAYETTE', 'ONAGA', 'ST MARYS', 'KANSAS CITY',
       'HOLTON', 'OVERLAND PARK', 'WICHITA', 'Berryton', 'LENEXA',
       'WINSTON SALEM', '*Unknown', 'FRANKLIN', 'NETAWAKA',
       'VALLEY FALLS', 'AUBURN', 'Atchison', 'Junction City', 'CHAPMAN',
       'HERINGTON', 'OVERBROOK', 'HANOVER'], dtype=object)

In [15]:
departments['DepartmentType'].unique()

array(['*Deleted', '*Not Applicable', '*Unspecified', '*Unknown', 'ED',
       'ICU', 'L&D', 'HOD', 'OR', 'Normal', nan, 'SNF/NF'], dtype=object)

In [19]:
departments['DepartmentSpecialty'].unique()

array(['*Deleted', '*Not Applicable', '*Unspecified',
       'Central Scheduling', 'Home Health Services', 'Hospice Services',
       'Emergency Medicine', 'Critical Care Medicine', 'Neonatology',
       'Obstetrics', 'Pediatrics', 'Hematology and Oncology',
       'Gastroenterology', 'Pain Medicine', 'Pharmacy',
       'Cardiac Rehabilitation', 'Radiology', 'Rheumatology', 'Lab',
       'Psychiatry', 'Physical Medicine and Rehabilitation',
       'Pre-Admission Testing', 'Pulmonology', 'Sleep Medicine',
       'Wound Care', 'Nutrition', 'Respiratory Therapy',
       'Case Management', 'Physical Therapy', 'Occupational Therapy',
       'Speech Therapy', 'Neurology', 'Anesthesiology', 'Otolaryngology',
       'Oncology', 'Radiation Therapy', 'Radiation Oncology',
       'Palliative Medicine', 'Infusion Therapy', 'Orthopedic Surgery',
       'Family Medicine', 'Nuclear Medicine', 'Internal Medicine',
       'Urgent Care', 'Dermatology', 'Cardiothoracic Surgery',
       'Obstetrics and Gynecology', 'Intensive Care',
       'Cardiac Intensive Care', 'General Surgery',
       'Neurological Intensive Care', 'Pediatric Intensive Care',
       'Surgical Intensive Care', 'Transplant', 'Nephrology',
       'Pediatric Gastroenterology', 'Pediatric Surgery',
       'Pediatric Emergency Medicine', 'Burn Surgery', 'Social Services',
       'Bariatrics', 'Cardiology', 'Allergy', 'Urology', 'Neurosurgery',
       'Endocrinology', 'Pediatric Endocrinology', 'Pediatric Cardiology',
       'Ophthalmology', 'Research', 'Plastic Surgery',
       'Infectious Diseases', 'Maternal and Fetal Medicine',
       'Addiction Medicine', 'Occupational Medicine',
       'Pediatric Critical Care Medicine', 'Diabetes Services',
       'Care Management', 'Pediatric Oncology',
       'Pediatric Physical Medicine and Rehabilitation',
       'Pediatric Radiology', 'Pediatric Allergy', 'Pediatric Audiology',
       'Pediatric Cardiothoracic Surgery', 'Pediatric Dermatology',
       'Developmental and Behavioral Pediatrics',
       'Pediatric Otolaryngology', 'Pediatric Genetics',
       'Pediatric Infectious Disease', 'Pediatric Nephrology',
       'Pediatric Neurology', 'Pediatric Neurosurgery',
       'Pediatric Occupational Therapy', 'Pediatric Ophthalmology',
       'Pediatric Orthopedic Surgery', 'Pediatric Physical Therapy',
       'Pediatric Plastic Surgery', 'Pediatric Psychiatry',
       'Pediatric Pulmonology', 'Pediatric Radiation Oncology',
       'Pediatric Rheumatology', 'Pediatric Social Services',
       'Pediatric Speech Therapy', 'Pediatric Urology',
       'Child and Adolescent Psychiatry', 'Genetics', 'Gerontology',
       'Gynecology', 'Pathology', 'Sports Medicine', 'Vascular Surgery',
       'Audiology', 'Dentistry', 'Chiropractic Medicine', 'Foot & Ankle',
       'Conversion', '*Unknown', 'Pediatric Hematology and Oncology', nan,
       'Primary Care', 'Behavioral Health'], dtype=object)

## Encounters data

In [29]:
encounters = pd.read_csv('encounters.csv')

encounters.head()

,Date,AdmissionInstant,AdmitYear,AdmitMonth,AdmitDay,AdmitHour,AdmitMinute,AdmissionSource,AdmissionType,DischargeInstant,...,AttendingProviderDurableKey,DischargeProviderDurableKey,DepartmentKey,PrimaryDiagnosisKey,IsEdVisit,IsHospitalAdmission,IsHospitalOutpatientVisit,IsInpatientAdmission,IsObservation,IsOutpatientFaceToFaceVisit
0,04/25/22,2022-04-25 20:33:00,2022.0,4.0,25.0,20.0,33.0,Non-Health Care Facility Point of Origin,Elective,2022-04-25 21:35:00,...,2982,2982,27,910699,0,1,0,0,1,0
1,04/29/22,2022-04-29 18:18:00,2022.0,4.0,29.0,18.0,18.0,Clinic/Physician Referral,Elective,2022-04-29 18:20:00,...,2979,2979,27,-1,0,1,0,0,1,0
2,01/10/22,2022-01-10 05:52:00,2022.0,1.0,10.0,5.0,52.0,Non-Health Care Facility Point of Origin,Elective,2022-01-12 11:43:00,...,6223,7015,27,468738,0,1,0,1,0,0
3,03/08/22,2022-03-08 09:08:00,2022.0,3.0,8.0,9.0,8.0,Non-Health Care Facility Point of Origin,Elective,2022-03-10 13:45:00,...,7973,7973,27,468492,0,1,0,1,0,0
4,03/16/22,2022-03-16 14:19:00,2022.0,3.0,16.0,14.0,19.0,Non-Health Care Facility Point of Origin,Elective,2022-03-16 16:00:00,...,6223,2982,27,907210,0,1,0,0,1,0

## Diagnosis data

In [36]:
diagnosis = pd.read_csv('diagnosis.csv')

diagnosis.head()

,DiagnosisKey,GroupName,GroupCode,DiagnosisName,DiagnosisValue
0,2.0,Typhoid and paratyphoid fevers,ICD-10-CM: A01,"Paratyphoid fever, unspecified( ICD-10-CM: A01...",A01.4
1,3.0,Respiratory tuberculosis,ICD-10-CM: A15,Primary respiratory tuberculosis( ICD-10-CM: A...,A15.7
2,7.0,Fracture at wrist and hand level,ICD-10-CM: S62,"Displaced fracture of pisiform, unspecified wr...",S62.163K
3,8.0,Fracture of rib,ICD-10-CM: S22,"Multiple fractures of ribs, right side, subseq...",S22.41XG
4,9.0,Fracture at wrist and hand level,ICD-10-CM: S62,Nondisplaced fracture of distal phalanx of lef...,S62.663G

`GroupName` and `GroupCode` are broader categories to look into.

In [87]:
diagnosis['GroupName'].str.contains('fracture', case=False).mean() # Fractures only make up 27% of diagnoses

# Dental, diabetes, burns, open wounds are still a much lower percentage than Fractures

0.2749856001128481

### Encounters x diagnosis data

In [90]:
df = pd.merge(encounters, diagnosis, left_on='PrimaryDiagnosisKey', right_on='DiagnosisKey')
df.head()

,Date,AdmissionInstant,AdmitYear,AdmitMonth,AdmitDay,AdmitHour,AdmitMinute,AdmissionSource,AdmissionType,DischargeInstant,...,IsHospitalAdmission,IsHospitalOutpatientVisit,IsInpatientAdmission,IsObservation,IsOutpatientFaceToFaceVisit,DiagnosisKey,GroupName,GroupCode,DiagnosisName,DiagnosisValue
0,04/25/22,2022-04-25 20:33:00,2022.0,4.0,25.0,20.0,33.0,Non-Health Care Facility Point of Origin,Elective,2022-04-25 21:35:00,...,1,0,0,1,0,910699.0,Maternal care for other conditions predominant...,ICD-10-CM: O26,"Other specified pregnancy related conditions, ...",O26.893
1,01/10/22,2022-01-10 05:52:00,2022.0,1.0,10.0,5.0,52.0,Non-Health Care Facility Point of Origin,Elective,2022-01-12 11:43:00,...,1,0,1,0,0,468738.0,Maternal care for abnormality of pelvic organs,ICD-10-CM: O34,Maternal care for low transverse scar from pre...,O34.211
2,03/08/22,2022-03-08 09:08:00,2022.0,3.0,8.0,9.0,8.0,Non-Health Care Facility Point of Origin,Elective,2022-03-10 13:45:00,...,1,0,1,0,0,468492.0,Pre-eclampsia,ICD-10-CM: O14,"Mild to moderate pre-eclampsia, complicating c...",O14.04
3,03/16/22,2022-03-16 14:19:00,2022.0,3.0,16.0,14.0,19.0,Non-Health Care Facility Point of Origin,Elective,2022-03-16 16:00:00,...,1,0,0,1,0,907210.0,Supervision of high risk pregnancy,ICD-10-CM: O09,Supervision of pregnancy with insufficient ant...,O09.30
4,02/10/22,2022-02-10 17:45:00,2022.0,2.0,10.0,17.0,45.0,Non-Health Care Facility Point of Origin,Elective,2022-02-13 13:00:00,...,1,0,1,0,0,468646.0,Gestational,ICD-10-CM: O13,Gestational (pregnancy-induced) hypertension w...,O13.4

In [106]:
df['GroupName'].value_counts().head(10)

GroupName
Encounter for general examination without complaint, suspected or reported diagnosis    498676
Other joint disorder, not elsewhere classified                                          264359
Type 2 diabetes mellitus                                                                232287
Essential                                                                               213658
Dorsalgia                                                                               177151
Long term                                                                               138552
Encounter for screening for malignant neoplasms                                         137367
Overweight and obesity                                                                  105518
Other and unspecified soft tissue disorders, not elsewhere classified                    97624
Atrial fibrillation and flutter                                                          83247
Name: count, dtype: int64

Encounter for screening for malignant neoplasms could be our focus.

In [113]:
list(df['GroupName'].unique())

['Maternal care for other conditions predominantly related to pregnancy',
 'Maternal care for abnormality of pelvic organs',
 'Pre-eclampsia',
 'Supervision of high risk pregnancy',
 'Gestational',
 'Preterm labor',
 'Hemangioma and lymphangioma, any site',
 'Melanocytic nevi',
 'Skin changes due to chronic exposure to nonionizing radiation',
 'Encounter for general examination without complaint, suspected or reported diagnosis',
 'Lichen simplex chronicus and prurigo',
 'Other and unspecified dermatitis',
 'Other disorders of pigmentation',
 'Encounter for screening for malignant neoplasms',
 'Personal history of malignant neoplasm',
 'Follicular cysts of skin and subcutaneous tissue',
 'Herpesviral',
 'Other nontoxic goiter',
 'Malignant melanoma of skin',
 'Glaucoma',
 'Keratitis',
 'Sleep disorders',
 'Benign neoplasm of meninges',
 'Essential',
 'Neoplasm of uncertain behavior of other and unspecified sites',
 'Viral warts',
 'Disorders of lipoprotein metabolism and other lipidemias',
 'Long term',
 'Type 2 diabetes mellitus',
 'Malignant neoplasm of thyroid gland',
 'Chronic ischemic heart disease',
 'Malignant neoplasm of tonsil',
 'Visual disturbances',
 'Other benign neoplasms of skin',
 'Other disorders of kidney and ureter, not elsewhere classified',
 'Disorders of lacrimal system',
 'Multiple sclerosis',
 'Otitis externa',
 'Other disorders of eyelid',
 'Other disorders of urinary system',
 "Alzheimer's disease",
 'Dementia in other diseases classified elsewhere',
 'Encounter for other special examination without complaint, suspected or reported diagnosis',
 'Postprocedural endocrine and metabolic complications and disorders, not elsewhere classified',
 'Personal history of certain other diseases',
 'Other disorders of bladder',
 'Heart failure',
 'Asthma',
 'Atopic dermatitis',
 'Osteoporosis without current pathological fracture',
 'Other symptoms and signs involving the circulatory and respiratory system',
 'Other abnormal findings of blood chemistry',
 'Malaise and fatigue',
 'Aphagia and dysphagia',
 'Male erectile dysfunction',
 'Gastro-esophageal reflux disease',
 'Other chronic obstructive pulmonary disease',
 'Chronic kidney disease',
 'Other anxiety disorders',
 'Urticaria',
 'Edema, not elsewhere classified',
 'Thyroiditis',
 'Pruritus',
 'Spondylosis',
 'Other specified health status',
 'Malignant neoplasm of other and unspecified parts of biliary tract',
 'Major depressive disorder, recurrent',
 'Seborrheic keratosis',
 'Other hypothyroidism',
 'Presence of other functional implants',
 'Other joint disorder, not elsewhere classified',
 'Problems related to lifestyle',
 'Major depressive disorder, single episode',
 'Type 1 diabetes mellitus',
 'Pain, not elsewhere classified',
 'Elevated blood glucose level',
 'Other specified diabetes mellitus',
 'Hypofunction and other disorders of the pituitary gland',
 'Disorders of autonomic nervous system',
 'Reaction to severe stress, and adjustment disorders',
 'Other cardiac arrhythmias',
 'Benign neoplasm of other and unspecified endocrine glands',
 'Acquired absence of organs, not elsewhere classified',
 'Reserved for concepts with insufficient information to code with codable children',
 'Other disorders of skin and subcutaneous tissue, not elsewhere classified',
 'Hematuria',
 'Abnormal tumor markers',
 'Diabetes mellitus due to underlying condition',
 'Atrial fibrillation and flutter',
 'Other and unspecified disorders of male genital organs',
 'Acne',
 'Symptoms and signs concerning food and fluid intake',
 'Psoriasis',
 'Thyrotoxicosis',
 'Osteoporosis with current pathological fracture',
 'Abnormal findings on diagnostic imaging of lung',
 'Estrogen receptor status',
 'Malignant neoplasm of breast',
 'Encounter for screening for other diseases and disorders',
 'Encounter for immunization',
 'Paroxysmal tachycardia',
 'Simple and mucopurulent chronic bronchitis',
 'Malignant neoplasm of liver and intrahepatic bile ducts',
 'Other disorders of bone density and structure',
 'Dizziness and giddiness',
 'Ovarian dysfunction',
 'Osteoarthritis of hip',
 'Infections of genitourinary tract in pregnancy',
 'Other postprocedural states',
 'Other disorders of arteries and arterioles',
 'Proteinuria',
 'Disorders of mineral metabolism',
 'Other disorders of veins',
 'Other symptoms and signs involving cognitive functions and awareness',
 'Benign prostatic hyperplasia',
 'Obstructive and reflux uropathy',
 'Age-related cataract',
 'Polyuria',
 'Aortic aneurysm and dissection',
 'Other epidermal thickening',
 'Unspecified chronic bronchitis',
 'Nonrheumatic aortic valve disorders',
 'Vasomotor and allergic rhinitis',
 'Migraine',
 'Abnormalities of heart beat',
 'Malignant neoplasm of prostate',
 'Disturbances of skin sensation',
 'Lymphoid leukemia',
 'Malignant neoplasm of pancreas',
 'Other disorders of carbohydrate metabolism',
 'Vitamin D deficiency',
 'Other follicular disorders',
 'Esophagitis',
 'Follicular lymphoma',
 'Pervasive developmental disorders',
 'Other and unspecified diseases of blood and blood-forming organs',
 'Rash and other nonspecific skin eruption',
 'Mature t/NK-cell lymphomas',
 'Iron deficiency anemia',
 'Hypertensive chronic kidney disease',
 'Other disorders of white blood cells',
 'COVID-19',
 'Rosacea',
 'Other systemic involvement of connective tissue',
 'Convulsions, not elsewhere classified',
 'Findings of drugs and other substances, not normally found in blood',
 'Other bacterial agents as the cause of diseases classified elsewhere',
 'Abnormal serum enzyme levels',
 'Other neoplasms of uncertain behavior of lymphoid, hematopoietic and related tissue',
 'Cough',
 'Purpura and other hemorrhagic conditions',
 'Overweight and obesity',
 'Bronchiectasis',
 'Other coagulation defects',
 'Sleep disorders not due to a substance or known physiological condition',
 'Nonrheumatic mitral valve disorders',
 'Congenital malformations of aortic and mitral valves',
 'Body mass index',
 'Polyosteoarthritis',
 'Calculus of kidney and ureter',
 'Non-follicular lymphoma',
 'Somnolence, stupor and coma',
 'Malignant neoplasm of stomach',
 'Occlusion and stenosis of precerebral arteries, not resulting in cerebral infarction',
 'Alcohol related disorders',
 'Other rheumatoid arthritis',
 'Dorsalgia',
 'Testicular dysfunction',
 'Other disorders of bone',
 'Other disorders of cartilage',
 'Pain in throat and chest',
 'Other anemias',
 'Other disorders of fluid, electrolyte and acid-base balance',
 'Retention of urine',
 'Abnormalities of breathing',
 'Disorders of purine and pyrimidine metabolism',
 'Transplanted organ and tissue status',
 'Other diseases of liver',
 'Unspecified nephritic syndrome',
 'Neoplasms of unspecified behavior',
 'Unspecified dementia',
 'Other retinal disorders',
 'Malignant neoplasm of corpus uteri',
 'Family history of primary malignant neoplasm',
 'Other disorders of external ear',
 'Problems related to housing and economic circumstances',
 'Cardiomyopathy',
 'Encounter for other aftercare and medical care',
 'Abnormal and inconclusive findings on diagnostic imaging of breast',
 'Other symptoms and signs involving the digestive system and abdomen',
 'Schizophrenia',
 'Other disorders of muscle',
 'Other congenital malformations of heart',
 'Acquired absence of limb',
 'Other and unspecified noninfective gastroenteritis and colitis',
 'Epilepsy and recurrent seizures',
 'Emphysema',
 'Personal risk factors, not elsewhere classified',
 'Injury of unspecified body region',
 'Open wound of knee and lower leg',
 'Personal history of other diseases and conditions',
 'Encounter for contraceptive management',
 'Family history of other specific disorders',
 'Other specified and unspecified types of non-Hodgkin lymphoma',
 'Other peripheral vascular diseases',
 'Malignant neoplasm of kidney, except renal pelvis',
 'Blindness and low vision',
 'Atrioventricular and left bundle-branch block',
 'Other disorders of adrenal gland',
 "Parkinson's disease",
 'Presence of cardiac and vascular implants and grafts',
 'Acute pharyngitis',
 'Bipolar disorder',
 'Malignant neuroendocrine tumors',
 'Pulmonary embolism',
 'Seborrheic dermatitis',
 'Malignant neoplasm of esophagus',
 'Abdominal and pelvic pain',
 'Other noninfective disorders of lymphatic vessels and lymph nodes',
 'Facial nerve disorders',
 'Other disorders of eye and adnexa',
 'Dislocation and sprain of joints and ligaments of knee',
 'Encounter for screening for infectious and parasitic diseases',
 'Lupus erythematosus',
 'Other and unspecified soft tissue disorders, not elsewhere classified',
 'Rheumatoid arthritis with rheumatoid factor',
 'Osteoarthritis of knee',
 'Adverse effects, not elsewhere classified',
 'Attention-deficit hyperactivity disorders',
 'Other and unspecified osteoarthritis',
 'Hyperparathyroidism and other disorders of parathyroid gland',
 'Hypertrophic disorders of skin',
 'Other diseases of lip and oral mucosa',
 'Malignant neoplasm of bladder',
 'Androgenic alopecia',
 'Anemia in chronic diseases classified elsewhere',
 'Secondary hypertension',
 'Fracture of lower leg, including ankle',
 'Thoracic, thoracolumbar, and lumbosacral intervertebral disc disorders',
 'Intracranial injury',
 'Abnormalities of gait and mobility',
 'Cerebral palsy',
 'Excessive, frequent and irregular menstruation',
 'Atherosclerosis',
 'Peptic ulcer, site unspecified',
 'Hypotension',
 'Diseases of capillaries',
 'Abnormality of red blood cells',
 'Irritable bowel syndrome',
 'Headache',
 'Other disorders of synovium and tendon',
 'Other congenital malformations of skin',
 'Cerebral infarction',
 'Other behavioral and emotional disorders with onset usually occurring in childhood and adolescence',
 'Other venous embolism and thrombosis',
 'Cellulitis and acute lymphangitis',
 'Other and unspecified malignant neoplasm of skin',
 'Problems related to care provider dependency',
 'Nonsuppurative otitis media',
 'Other and unspecified abnormal findings in urine',
 'Other and unspecified metabolic disorders',
 'Abnormal findings in specimens from other organs, systems and tissues',
 'Nicotine dependence',
 'Vascular disorders of intestine',
 'Other abnormal immunological findings in serum',
 'Malignant neoplasm of bronchus and lung',
 'Hereditary and idiopathic neuropathy',
 'Unspecified intellectual disabilities',
 'Cholelithiasis',
 'Non-pressure chronic ulcer of lower limb, not elsewhere classified',
 'Malignant neoplasm without specification of site',
 'Secondary malignant neoplasm of respiratory and digestive organs',
 'Cystic kidney disease',
 'Fibroblastic disorders',
 'Menopausal and other perimenopausal disorders',
 'Dental caries',
 'Other and unspecified arthropathy',
 'Abnormal results of function studies',
 'Respiratory failure, not elsewhere classified',
 'Other interstitial pulmonary diseases',
 'Deficiency of other b group vitamins',
 'Hodgkin lymphoma',
 'Unspecified mood',
 'Hemorrhoids and perianal venous thrombosis',
 'Volume depletion',
 'Ankylosing spondylitis',
 'Impetigo',
 'Hyperfunction of pituitary gland',
 'Poisoning by, adverse effect of and underdosing of agents primarily affecting the cardiovascular system',
 'Other extrapyramidal and movement disorders',
 'Deficiency of other nutrient elements',
 'Other problems related to primary support group, including family circumstances',
 'Acquired hemolytic anemia',
 'Other acantholytic disorders',
 'Personal history of medical treatment',
 'Other and unspecified hearing loss',
 'Symptoms and signs involving emotional state',
 'Malignant neoplasm of colon',
 'Cardiac murmurs and other cardiac sounds',
 'Hypertrichosis',
 'Injury of muscle, fascia and tendon at lower leg level',
 'Other disorders of ear, not elsewhere classified',
 'Intestinal malabsorption',
 'Other symptoms and signs involving the nervous and musculoskeletal systems',
 'Pulmonary eosinophilia, not elsewhere classified',
 'Other headache syndromes',
 'Chronic sinusitis',
 'Genetic susceptibility to disease',
 'Unspecified jaundice',
 'Other and unspecified symptoms and signs involving the genitourinary system',
 'Fracture of foot and toe, except ankle',
 'Other inflammatory liver diseases',
 'Other and unspecified injuries of head',
 'Myasthenia gravis and other myoneural disorders',
 'Angina pectoris',
 'Dermatophytosis',
 'Other acquired deformities of limbs',
 'Localized swelling, mass and lump of skin and subcutaneous tissue',
 'Carrier of infectious disease',
 'Malignant neoplasm of oropharynx',
 'Carcinoma in situ of breast',
 'Other nutritional anemias',
 'Persons encountering health services for other counseling and medical advice, not elsewhere classified',
 'Disorders of orbit',
 "Crohn's disease",
 'Ulcerative colitis',
 'Generalized hyperhidrosis',
 'Other skin changes',
 'Persons encountering health services in other circumstances',
 'Other disorders of breast',
 'Other disorders of penis',
 'Other nonscarring hair loss',
 'Other diseases of esophagus',
 'Hydrocephalus',
 'Other diseases of digestive system',
 'Benign lipomatous neoplasm',
 'Other disorders of psychological development',
 'Abnormal findings on diagnostic imaging of other body structures',
 'Pain associated with micturition',
 'Synovitis and tenosynovitis',
 'Vitiligo',
 'Other disorders of iris and ciliary body',
 'Cystitis',
 'Other functional intestinal disorders',
 'Other necrotizing vasculopathies',
 'Congenital malformations of cardiac septa',
 'Malignant neoplasm of rectum',
 'Pain, unspecified',
 'Osteoarthritis of first carpometacarpal joint',
 'Chronic gout',
 'Systemic lupus erythematosus',
 'Other degenerative diseases of nervous system, not elsewhere classified',
 'Malignant neoplasm of brain',
 'Reserved for inherently not codable concepts without codable children',
 'Encounter for follow-up examination after completed treatment for conditions other than malignant neoplasm',
 'Other conduction disorders',
 'Cardiac arrest',
 'Other inflammation of eyelid',
 'Other and unspecified polyneuropathies',
 'Other contact with and',
 'Otalgia and effusion of ear',
 'Abnormal involuntary movements',
 'Other spondylopathies',
 'Other pulmonary heart diseases',
 'Allergic contact dermatitis',
 'Iridocyclitis',
 'Peritonitis',
 'Arterial embolism and thrombosis',
 'Transient cerebral ischemic attacks and related syndromes',
 'Presence of other devices',
 'Granulomatous disorders of skin and subcutaneous tissue',
 'Other and unspecified disorders of nose and nasal sinuses',
 'Artificial opening status',
 'Family history of certain disabilities and chronic diseases',
 'Sickle-cell disorders',
 'Immunodeficiency with predominantly antibody defects',
 'Resistant hypertension',
 'Pleural effusion, not elsewhere classified',
 'Mononeuropathies of upper limb',
 'Polyglandular dysfunction',
 'Rheumatic mitral valve diseases',
 'Malignant neoplasm of gallbladder',
 'Acute sinusitis',
 'Atrophic disorders of skin',
 'Down syndrome',
 'Malignant neoplasm of cervix uteri',
 'Malignant neoplasm of testis',
 'Malignant neoplasm of ovary',
 'Other local infections of skin and subcutaneous tissue',
 'Abnormal blood-pressure reading, without diagnosis',
 'Shoulder lesions',
 'Diseases of tongue',
 'Other osteochondrodysplasias',
 'Polyneuropathy in diseases classified elsewhere',
 'Other aplastic anemias and other bone marrow failure syndromes',
 'Pemphigoid',
 'Acanthosis nigricans',
 'Other diseases of pancreas',
 'Eccrine sweat disorders',
 'Gout',
 'Iodine-deficiency related thyroid disorders and allied conditions',
 'Enlarged lymph nodes',
 'Acute kidney failure',
 'Other aneurysm',
 'Unspecified fall',
 'Vitamin B12 deficiency anemia',
 'Other immunodeficiencies',
 'Congenital malformations of cardiac chambers and connections',
 'Juvenile arthritis',
 'Conjunctivitis',
 'Encounter for administrative examination',
 'Umbilical hernia',
 'Chronic diseases of tonsils and adenoids',
 'Traumatic amputation of wrist, hand and fingers',
 'Other disorders of conjunctiva',
 'Varicose veins of lower extremities',
 'Zoster',
 'Fracture of cervical vertebra and other parts of neck',
 'Chronic rhinitis, nasopharyngitis and pharyngitis',
 'Infection due to other mycobacteria',
 'Hypertensive heart and chronic kidney disease',
 'Malignant neoplasm of other connective and soft tissue',
 'Benign neuroendocrine tumors',
 'Malignant neoplasm of rectosigmoid junction',
 'Other general symptoms and signs',
 'Other congenital malformations of urinary system',
 'Complications and ill-defined descriptions of heart disease',
 'Disorders resulting from impaired renal tubular function',
 'zzdonotuse errenc',
 'Disorders of prepuce',
 'Mental disorder, not otherwise specified',
 'Renal agenesis and other reduction defects of kidney',
 'Other respiratory disorders',
 'Nail disorders',
 'Malignant neoplasm of penis',
 'Neuromuscular dysfunction of bladder, not elsewhere classified',
 'Human immunodeficiency virus',
 'Acute pancreatitis',
 'Disorders of porphyrin and bilirubin metabolism',
 'Malignant neoplasm of base of tongue',
 'Other cataract',
 'Benign neoplasm of brain and other parts of central nervous system',
 'Bronchitis, not specified as acute or chronic',
 'Malignant neoplasm of ureter',
 'Other cerebrovascular diseases',
 'Lack of expected normal physiological development in childhood and adults',
 'Unspecified lump in breast',
 'Polycythemia vera',
 'Other abnormal uterine and vaginal bleeding',
 'Hypoparathyroidism',
 'Other and unspecified injuries of ankle and foot',
 'Subclinical iodine-deficiency hypothyroidism',
 'Systemic sclerosis',
 'Gastritis and duodenitis',
 'Poisoning by, adverse effect of and underdosing of nonopioid analgesics, antipyretics and antirheumatics',
 'Other diseases of gallbladder',
 'Retinal vascular occlusions',
 'Other disorders of thyroid',
 'Heartburn',
 'Disorders of globe',
 'Chronic viral hepatitis',
 'Other disorders of brain',
 'Intraoperative and postprocedural complications and disorders of digestive system, not elsewhere classified',
 'Toxic effect of contact with venomous animals and plants',
 'Other endocrine disorders',
 'Fever of other and unknown origin',
 'Other disorders of optic',
 'Other disorders of cornea',
 'Fracture of femur',
 'Abnormal findings in specimens from female genital organs',
 'Vasculitis limited to skin, not elsewhere classified',
 'Congenital malformations of lung',
 'Other specific joint derangements',
 'Fracture of lumbar spine and pelvis',
 'Other maternal diseases classifiable elsewhere but complicating pregnancy, childbirth and the puerperium',
 'Neoplasm of uncertain behavior of endocrine glands',
 'Disorders of trigeminal nerve',
 'Dislocation and sprain of joints and ligaments at ankle, foot and toe level',
 'Hereditary factor VIII deficiency',
 'Paralytic ileus and intestinal obstruction without hernia',
 'Speech disturbances, not elsewhere classified',
 'Soft tissue disorders related to use, overuse and pressure',
 'Pain and other conditions associated with female genital organs and menstrual cycle',
 'Other predominantly sexually transmitted diseases, not elsewhere classified',
 'Other inflammatory spondylopathies',
 'Malignant immunoproliferative diseases and certain other b-cell lymphomas',
 'Other and unspecified disorders of eustachian tube',
 'Asymptomatic human immunodeficiency virus',
 'Specific developmental disorders of speech and language',
 'Hereditary ataxia',
 'Dislocation and sprain of joint and ligaments of hip',
 'Other disorders of pancreatic internal secretion',
 'Other conditions of integument specific to newborn',
 'Neutropenia',
 'Injury of muscle, fascia and tendon at neck level',
 'Cryptococcosis',
 'Complications of procedures, not elsewhere classified',
 'Myelodysplastic syndromes',
 'Recurrent and persistent hematuria',
 'Other diseases of inner ear',
 'Male infertility',
 'Other hereditary hemolytic anemias',
 'Disorders of vestibular function',

In [133]:
list(df.loc[df['GroupName'].str.contains('malignant', case=False, na=False), 'GroupName'].unique())

['Encounter for screening for malignant neoplasms',
 'Personal history of malignant neoplasm',
 'Malignant melanoma of skin',
 'Malignant neoplasm of thyroid gland',
 'Malignant neoplasm of tonsil',
 'Malignant neoplasm of other and unspecified parts of biliary tract',
 'Malignant neoplasm of breast',
 'Malignant neoplasm of liver and intrahepatic bile ducts',
 'Malignant neoplasm of prostate',
 'Malignant neoplasm of pancreas',
 'Malignant neoplasm of stomach',
 'Malignant neoplasm of corpus uteri',
 'Family history of primary malignant neoplasm',
 'Malignant neoplasm of kidney, except renal pelvis',
 'Malignant neuroendocrine tumors',
 'Malignant neoplasm of esophagus',
 'Malignant neoplasm of bladder',
 'Other and unspecified malignant neoplasm of skin',
 'Malignant neoplasm of bronchus and lung',
 'Malignant neoplasm without specification of site',
 'Secondary malignant neoplasm of respiratory and digestive organs',
 'Malignant neoplasm of colon',
 'Malignant neoplasm of oropharynx',
 'Malignant neoplasm of rectum',
 'Malignant neoplasm of brain',
 'Encounter for follow-up examination after completed treatment for conditions other than malignant neoplasm',
 'Malignant neoplasm of gallbladder',
 'Malignant neoplasm of cervix uteri',
 'Malignant neoplasm of testis',
 'Malignant neoplasm of ovary',
 'Malignant neoplasm of other connective and soft tissue',
 'Malignant neoplasm of rectosigmoid junction',
 'Malignant neoplasm of penis',
 'Malignant neoplasm of base of tongue',
 'Malignant neoplasm of ureter',
 'Malignant immunoproliferative diseases and certain other b-cell lymphomas',
 'Secondary malignant neoplasm of other and unspecified sites',
 'Secondary and unspecified malignant neoplasm of lymph nodes',
 'Malignant neoplasm of larynx',
 'Malignant neoplasm of nasopharynx',
 'Malignant neoplasm of vulva',
 'Malignant neoplasm of other and ill-defined sites',
 'Malignant neoplasm of anus and anal canal',
 'Multiple myeloma and malignant plasma cell neoplasms',
 'Malignant neoplasm of uterus, part unspecified',
 'Encounter for follow-up examination after completed treatment for malignant neoplasm',
 'Malignant neoplasm of nasal cavity and middle ear',
 'Malignant neoplasm of lip',
 'Malignant neoplasm of renal pelvis',
 'Malignant neoplasm of other and ill-defined digestive organs',
 'Malignant neoplasm of small intestine',
 'Malignant neoplasm of other and unspecified parts of mouth',
 'Maternal malignant neoplasms, traumatic injuries and abuse classifiable elsewhere but complicating pregnancy, childbirth and the puerperium',
 'Malignant neoplasm of other and unspecified parts of tongue',
 'Malignant neoplasm of thymus',
 'Malignant neoplasm of peripheral nerves and autonomic nervous system',
 'Malignant neoplasm of floor of mouth',
 'Malignant neoplasm of eye and adnexa',
 'Malignant neoplasm of bone and articular cartilage of other and unspecified sites',
 'Other and unspecified malignant neoplasms of lymphoid, hematopoietic and related tissue',
 'Malignant neoplasm of retroperitoneum and peritoneum',
 'Malignant neoplasm of hypopharynx',
 'Malignant neoplasm of accessory sinuses',
 'Malignant neoplasm of other and ill-defined sites in the lip, oral cavity and pharynx',
 'Malignant neoplasm of other and unspecified urinary organs',
 'Malignant neoplasm of parotid gland',
 'Malignant neoplasm of other endocrine glands and related structures',
 'Malignant neoplasm of pyriform sinus',
 'Malignant neoplasm of palate',
 'Malignant neoplasm of gum',
 'Malignant neoplasm of meninges',
 'Malignant neoplasm of spinal cord, cranial nerves and other parts of central nervous system',
 'Malignant neoplasm of heart, mediastinum and pleura',
 'Malignant neoplasm of adrenal gland',
 'Malignant neoplasm of other and unspecified female genital organs',
 'Malignant neoplasm of bone and articular cartilage of limbs',
 'Malignant neoplasm of other and unspecified major salivary glands',
 'Malignant neoplasm of other and unspecified male genital organs',
 'Malignant neoplasm of vagina',
 'Malignant neoplasm of other and ill-defined sites in the respiratory system and intrathoracic organs',
 'Malignant neoplasm of trachea',
 'Malignant neoplasm of placenta']

### What percentage of encounters are fractures/cancer?

In [120]:
df['FRACTURE'] = df['GroupName'].str.contains('fracture', case=False, na=False).astype(int)
df['CANCER'] = df['GroupName'].str.contains('malignant', case=False, na=False).astype(int)

In [124]:
df['FRACTURE'].mean() * 100

2.1578076078355464

In [126]:
df['CANCER'].mean() * 100

5.971879264496854

In [131]:
(df['GroupName'] == 'Encounter for general examination without complaint, suspected or reported diagnosis').mean() * 100

# From this, we can see that although percentages of fracture and cancer are low, they are not as low when compared to the most common diagnosis.

7.64878852052856

Could look into visit types associated to different diagnoses.

## Patient data

In [43]:
patients = pd.read_csv('patients.csv')

patients.head()

,CensusBlockGroupFipsCode,DurableKey,FirstRace,MaritalStatus,MyChartStatus,OmbEthnicity,OmbRace,SexAssignedAtBirth,SexualOrientation,SmokingStatus,VitalStatus,PatientBirthYearBin
0,201770007002,5.0,White or Caucasian,Single,Activated,Not Hispanic or Latino,White,*Unspecified,*Unspecified,Never,Alive,1970.0
1,*Unspecified,8.0,White or Caucasian,*Unspecified,Inactivated,Unknown,White,*Unspecified,*Unspecified,*Unknown,Alive,1980.0
2,*Unspecified,9.0,"Hispanic, Latino, or Spanish",Married,*Unspecified,Unknown,Some Other Race,*Unspecified,*Unspecified,Never,Alive,1955.0
3,*Unspecified,11.0,"Hispanic, Latino, or Spanish",Unknown,*Unspecified,Hispanic or Latino,Some Other Race,*Unspecified,*Unspecified,Never,Alive,1970.0
4,*Unspecified,12.0,Black or African American,Single,*Unspecified,Not Hispanic or Latino,Black or African American,*Unspecified,*Unspecified,Never,Alive,1980.0