In [81]:
import pandas as pd
import numpy as np

In [82]:
encounters = pd.read_csv("encounters.csv")
patients = pd.read_csv('patients.csv')
diagnosis = pd.read_csv('diagnosis.csv')
departments = pd.read_csv('departments.csv')
providers = pd.read_csv('providers.csv')
social_determinants = pd.read_csv('social_determinants.csv')
tigercensuscodes = pd.read_csv('tigercensuscodes.csv')

/var/folders/vs/1w9d81ds1959mg4v577160gr0000gn/T/ipykernel_65265/1187031051.py:6: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  social_determinants = pd.read_csv('social_determinants.csv')

In [83]:
encounters.head()

,Date,AdmissionInstant,AdmitYear,AdmitMonth,AdmitDay,AdmitHour,AdmitMinute,AdmissionSource,AdmissionType,DischargeInstant,...,AttendingProviderDurableKey,DischargeProviderDurableKey,DepartmentKey,PrimaryDiagnosisKey,IsEdVisit,IsHospitalAdmission,IsHospitalOutpatientVisit,IsInpatientAdmission,IsObservation,IsOutpatientFaceToFaceVisit
0,04/25/22,2022-04-25 20:33:00,2022.0,4.0,25.0,20.0,33.0,Non-Health Care Facility Point of Origin,Elective,2022-04-25 21:35:00,...,2982,2982,27,910699,0,1,0,0,1,0
1,04/29/22,2022-04-29 18:18:00,2022.0,4.0,29.0,18.0,18.0,Clinic/Physician Referral,Elective,2022-04-29 18:20:00,...,2979,2979,27,-1,0,1,0,0,1,0
2,01/10/22,2022-01-10 05:52:00,2022.0,1.0,10.0,5.0,52.0,Non-Health Care Facility Point of Origin,Elective,2022-01-12 11:43:00,...,6223,7015,27,468738,0,1,0,1,0,0
3,03/08/22,2022-03-08 09:08:00,2022.0,3.0,8.0,9.0,8.0,Non-Health Care Facility Point of Origin,Elective,2022-03-10 13:45:00,...,7973,7973,27,468492,0,1,0,1,0,0
4,03/16/22,2022-03-16 14:19:00,2022.0,3.0,16.0,14.0,19.0,Non-Health Care Facility Point of Origin,Elective,2022-03-16 16:00:00,...,6223,2982,27,907210,0,1,0,0,1,0

In [84]:
patients.head()

,CensusBlockGroupFipsCode,DurableKey,FirstRace,MaritalStatus,MyChartStatus,OmbEthnicity,OmbRace,SexAssignedAtBirth,SexualOrientation,SmokingStatus,VitalStatus,PatientBirthYearBin
0,201770007002,5.0,White or Caucasian,Single,Activated,Not Hispanic or Latino,White,*Unspecified,*Unspecified,Never,Alive,1970.0
1,*Unspecified,8.0,White or Caucasian,*Unspecified,Inactivated,Unknown,White,*Unspecified,*Unspecified,*Unknown,Alive,1980.0
2,*Unspecified,9.0,"Hispanic, Latino, or Spanish",Married,*Unspecified,Unknown,Some Other Race,*Unspecified,*Unspecified,Never,Alive,1955.0
3,*Unspecified,11.0,"Hispanic, Latino, or Spanish",Unknown,*Unspecified,Hispanic or Latino,Some Other Race,*Unspecified,*Unspecified,Never,Alive,1970.0
4,*Unspecified,12.0,Black or African American,Single,*Unspecified,Not Hispanic or Latino,Black or African American,*Unspecified,*Unspecified,Never,Alive,1980.0

In [85]:
diagnosis.head()

,DiagnosisKey,GroupName,GroupCode,DiagnosisName,DiagnosisValue
0,2.0,Typhoid and paratyphoid fevers,ICD-10-CM: A01,"Paratyphoid fever, unspecified( ICD-10-CM: A01...",A01.4
1,3.0,Respiratory tuberculosis,ICD-10-CM: A15,Primary respiratory tuberculosis( ICD-10-CM: A...,A15.7
2,7.0,Fracture at wrist and hand level,ICD-10-CM: S62,"Displaced fracture of pisiform, unspecified wr...",S62.163K
3,8.0,Fracture of rib,ICD-10-CM: S22,"Multiple fractures of ribs, right side, subseq...",S22.41XG
4,9.0,Fracture at wrist and hand level,ICD-10-CM: S62,Nondisplaced fracture of distal phalanx of lef...,S62.663G

In [86]:
departments.head()

,DepartmentKey,Address,City,County,DepartmentName,DepartmentSpecialty,DepartmentType,PostalCode,CensusTract
0,-3,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,NaN
1,-2,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,NaN
2,-1,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,NaN
3,1,1500 SW 10th ST,TOPEKA,*Unspecified,INITIAL DEPT,*Unspecified,*Unknown,66604,2.017700e+10
4,2,1979 Milky Way,VERONA,*Unspecified,EHS UM DEPT,*Unspecified,*Unknown,53593,5.502501e+10

In [87]:
providers
# look into this 
# providers is a person working within a department who provides heath care, such as  a technician, physician, or nurse practitioner.
# this file provides info about where this person works + their medical specialty
# ClinitianTitle - official Licensures of the care provider (i.e. Registered Nurse, Medical Doctor, etc.)	
# DurableKey - Links to patients file via ProviderDurableKey	
# OfficeAddress	Address of provider's primary work location	
# OfficePostalCode	Postal (Zip) Code of provider's primary work location	
# OfficeCity	City of provider's primary work location	
# PrimaryDepartment	The primary location  at which the provider sees  most of their patients.	
# PrimarySpecialty	The provider's specialty. What kind of patients and conditions do they see.	
# Type	e.g. physician, nurse practitioner, therapist, the field of the provider. A slightly higher level of description than Clinicial Title, which provides more detail. Provides general description of ClinicianTitle.

# explore null values in providers.csv
providers.isnull().sum()	
# large number of missing values for ClinicianTitle, OfficeAddress, OfficePostalCode, OfficeCity, and PrimarySpecialty.
# What to do from here?
# want to look at the specific providers with missing values and see if there are any patterns in the data that could help us fill in the missing values.

providers[providers['ClinicianTitle'].isnull()]
# unsure if there are any patterns in the data that could help us fill in the missing values for ClinicianTitle.


providers[providers['OfficeAddress'].isnull()]
# i see a lot of nursing students with missing values for OfficeAddress, OfficePostalCode, and OfficeCity. This could be because they are not yet assigned to a specific location or department within the healthcare system.

providers[providers['PrimarySpecialty'].isnull()]
providers[providers['PrimarySpecialty'].isnull()]['Type'].unique()
# for a lot of these, it looks like they are assistants, nurses, or nursing students, as well as therapists or counselors. This could be because they do not have a specific medical specialty, or because their specialty is not relevant to the care they provide.

providers.isnull().sum()

DurableKey                0
ClinicianTitle       113067
OfficeAddress         30335
OfficeCity            30344
OfficePostalCode      30362
PrimaryDepartment         0
PrimarySpecialty      37856
Type                      0
dtype: int64

In [88]:
social_determinants.head()

# merge with provided supporting dataset to remove null values 
# has a category for transportation 

# social determinants

    DisplayName AnswerText  EncounterKey  PatientDurableKey Domain
0  *Unspecified    Unknown   147506236.0                5.0    NaN
1  *Unspecified      Never   154008498.0          6094715.0    NaN
2  *Unspecified      Never   152425953.0          6094715.0    NaN
3  *Unspecified       Past   153702939.0                5.0    NaN
4  *Unspecified       Past   152713763.0                5.0    NaN

In [89]:
patients.head() 

# want to see which values in patients are *Unspecified for their census block 
patients[patients['CensusBlockGroupFipsCode'].isnull()]

Empty DataFrame
Columns: [CensusBlockGroupFipsCode, DurableKey, FirstRace, MaritalStatus, MyChartStatus, OmbEthnicity, OmbRace, SexAssignedAtBirth, SexualOrientation, SmokingStatus, VitalStatus, PatientBirthYearBin]
Index: []

In [90]:
# Our high-level game plan 
# choosing to focus on transportation / geographic access as our social determinant of health for this project, as it is a common barrier to healthcare access and can have a significant impact on patient outcomes.
# also choosing 2 core diagnosis families / types to focus one: one longer term (cancer) and one shorter term (fractures). This will allow us to compare and contrast the impact of transportation barriers on different types of health conditions, and to identify any unique challenges or opportunities for improving access to care for patients with these conditions.
# for each diagnosis family, we want to look at average visitations needed per patient and average staying time, and segment by region to see if there are any geographic patterns in healthcare utilization and outcomes for patients with transportation barriers.


# Fractures
diagnosis['GroupName'].str.contains('fracture', case=False).mean()

# merge encounters and diagnosis datasets
encounters_diagnosis = pd.merge(encounters, diagnosis, left_on='PrimaryDiagnosisKey', right_on='DiagnosisKey')

In [91]:
encounters_diagnosis.head()

# generate column names of encounters_diagnosis
encounters_diagnosis.columns

Index(['Date', 'AdmissionInstant', 'AdmitYear', 'AdmitMonth', 'AdmitDay',
       'AdmitHour', 'AdmitMinute', 'AdmissionSource', 'AdmissionType',
       'DischargeInstant', 'DischargeYear', 'DischargeMonth', 'DischargeDay',
       'DischargeHour', 'DischargeMinute', 'EncounterKey', 'PatientDurableKey',
       'Type', 'VisitType', 'VisitTypeDescription', 'ProviderDurableKey',
       'AttendingProviderDurableKey', 'DischargeProviderDurableKey',
       'DepartmentKey', 'PrimaryDiagnosisKey', 'IsEdVisit',
       'IsHospitalAdmission', 'IsHospitalOutpatientVisit',
       'IsInpatientAdmission', 'IsObservation', 'IsOutpatientFaceToFaceVisit',
       'DiagnosisKey', 'GroupName', 'GroupCode', 'DiagnosisName',
       'DiagnosisValue'],
      dtype='object')

In [92]:
# filter for fractures
fractures = encounters_diagnosis[encounters_diagnosis['GroupName'].str.contains('fracture', case=False)]
fractures

# look at all GroupNames for fractures
fractures['GroupName'].unique()

# Filter out 'osteoporosis without current pathological fracture' from dataset
fractures = fractures[~fractures['GroupName'].str.contains('osteoporosis without current pathological fracture', case=False)]
fractures['GroupName'].unique()

array(['Osteoporosis with current pathological fracture',
       'Fracture of lower leg, including ankle',
       'Fracture of foot and toe, except ankle',
       'Fracture of cervical vertebra and other parts of neck',
       'Fracture of femur', 'Fracture of lumbar spine and pelvis',
       'Fracture of rib', 'Fracture of shoulder and upper arm',
       'Fracture at wrist and hand level',
       'Periprosthetic fracture around internal prosthetic joint',
       'Fracture of forearm', 'Fracture of skull and facial bones'],
      dtype=object)

In [93]:
# calculate average visitations needed per patient for fractures
fractures_visitations = fractures.groupby('PatientDurableKey')['EncounterKey'].nunique().mean()
print(f"Average visitations needed per patient for fractures: {fractures_visitations}")

Average visitations needed per patient for fractures: 5.471346021311562

In [94]:
# Take the patient.csv dataset and encounters.csv dataset and merge them together on the PatientDurableKey column. This will allow us to have access to the patient's census block group information. 

# start with patients.csv 
patients
patients.columns 
# key columns: CensusBlockGroupFipsCode, DurableKey

patients = patients[
    patients["CensusBlockGroupFipsCode"].notna() &
    (patients["CensusBlockGroupFipsCode"] != "*Unspecified")
] # removing patients with null or unspecified census block group information - unsure whether or not to do this 

tigercensuscodes.head()

tigercensuscodes["GEOID"] = tigercensuscodes["GEOID"].astype(str)
tigercensuscodes["CountyFips"] = tigercensuscodes["GEOID"].str[:5]


tiger_geo = tigercensuscodes[[
    "GEOID",
    "CountyFips",
    "CENTLAT",
    "CENTLON",
    "PopulationValue"
]]


patients_geo = patients.merge(
    tiger_geo,
    left_on="CensusBlockGroupFipsCode",
    right_on="GEOID",
    how="left"
)


encounters_geo = encounters.merge(
    patients_geo[
        [
            "DurableKey",          # patient identifier
            "CountyFips",
            "CENTLAT",
            "CENTLON",
            "PopulationValue"
        ]
    ],
    left_on="PatientDurableKey",   # from encounters
    right_on="DurableKey",         # from patients
    how='left'
)

In [95]:
encounters_geo.head()

,Date,AdmissionInstant,AdmitYear,AdmitMonth,AdmitDay,AdmitHour,AdmitMinute,AdmissionSource,AdmissionType,DischargeInstant,...,IsHospitalAdmission,IsHospitalOutpatientVisit,IsInpatientAdmission,IsObservation,IsOutpatientFaceToFaceVisit,DurableKey,CountyFips,CENTLAT,CENTLON,PopulationValue
0,04/25/22,2022-04-25 20:33:00,2022.0,4.0,25.0,20.0,33.0,Non-Health Care Facility Point of Origin,Elective,2022-04-25 21:35:00,...,1,0,0,1,0,86333.0,20177,39.038987,-95.644925,1210.0
1,04/29/22,2022-04-29 18:18:00,2022.0,4.0,29.0,18.0,18.0,Clinic/Physician Referral,Elective,2022-04-29 18:20:00,...,1,0,0,1,0,626973.0,20177,39.053098,-95.720976,890.0
2,01/10/22,2022-01-10 05:52:00,2022.0,1.0,10.0,5.0,52.0,Non-Health Care Facility Point of Origin,Elective,2022-01-12 11:43:00,...,1,0,1,0,0,NaN,NaN,NaN,NaN,NaN
3,03/08/22,2022-03-08 09:08:00,2022.0,3.0,8.0,9.0,8.0,Non-Health Care Facility Point of Origin,Elective,2022-03-10 13:45:00,...,1,0,1,0,0,385246.0,20177,39.023433,-95.660754,1687.0
4,03/16/22,2022-03-16 14:19:00,2022.0,3.0,16.0,14.0,19.0,Non-Health Care Facility Point of Origin,Elective,2022-03-16 16:00:00,...,1,0,0,1,0,NaN,NaN,NaN,NaN,NaN

In [96]:
# % of encounters missing county
missing_county_pct = encounters_geo["CountyFips"].isna().mean()
print(f"Missing county: {missing_county_pct:.2%}")

# Ensure each patient maps to exactly one county
patients_geo.groupby("DurableKey")["CountyFips"].nunique().describe()

Missing county: 27.92%

count    336514.000000
mean          0.997750
std           0.047376
min           0.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: CountyFips, dtype: float64

In [97]:
county_mapping = pd.DataFrame({
    "CountyCode": [
        "001","003","005","007","009","011","013","015","017","019","021","023","025","027",
        "029","031","033","035","037","039","041","043","045","047","049","051","053","055",
        "057","059","061","063","065","067","069","071","073","075","077","079","081","083",
        "085","087","089","091","093","095","097","099","101","103","105","107","109","111",
        "113","115","117","119","121","123","125","127","129","131","133","135","137","139",
        "141","143","145","147","149","151","153","155","157","159","161","163","165","167",
        "169","171","173","175","177","179","181","183","185","187","189","191","193","195",
        "197","199","201","203","205","207","209"
    ],
    "CountyName": [
        "Allen","Anderson","Atchison","Barber","Barton","Bourbon","Brown","Butler","Chase",
        "Chautauqua","Cherokee","Cheyenne","Clark","Clay","Cloud","Coffey","Comanche","Cowley",
        "Crawford","Decatur","Dickinson","Doniphan","Douglas","Edwards","Elk","Ellis","Ellsworth",
        "Finney","Ford","Franklin","Geary","Gove","Graham","Grant","Gray","Greeley","Greenwood",
        "Hamilton","Harper","Harvey","Haskell","Hodgeman","Jackson","Jefferson","Jewell",
        "Johnson","Kearny","Kingman","Kiowa","Labette","Lane","Leavenworth","Lincoln","Linn",
        "Logan","Lyon","McPherson","Marion","Marshall","Meade","Miami","Mitchell","Montgomery",
        "Morris","Morton","Nemaha","Neosho","Ness","Norton","Osage","Osborne","Ottawa","Pawnee",
        "Phillips","Pottawatomie","Pratt","Rawlins","Reno","Republic","Rice","Riley","Rooks",
        "Rush","Russell","Saline","Scott","Sedgwick","Seward","Shawnee","Sheridan","Sherman",
        "Smith","Stafford","Stanton","Stevens","Sumner","Thomas","Trego","Wabaunsee","Wallace",
        "Washington","Wichita","Wilson","Woodson","Wyandotte"
    ]
})

In [98]:
encounters_geo["CountyCode"] = encounters_geo["CountyFips"].str[-3:]


encounters_geo = encounters_geo.merge(
    county_mapping,
    on="CountyCode",
    how="left"
)

encounters_geo.head()

,Date,AdmissionInstant,AdmitYear,AdmitMonth,AdmitDay,AdmitHour,AdmitMinute,AdmissionSource,AdmissionType,DischargeInstant,...,IsInpatientAdmission,IsObservation,IsOutpatientFaceToFaceVisit,DurableKey,CountyFips,CENTLAT,CENTLON,PopulationValue,CountyCode,CountyName
0,04/25/22,2022-04-25 20:33:00,2022.0,4.0,25.0,20.0,33.0,Non-Health Care Facility Point of Origin,Elective,2022-04-25 21:35:00,...,0,1,0,86333.0,20177,39.038987,-95.644925,1210.0,177,Shawnee
1,04/29/22,2022-04-29 18:18:00,2022.0,4.0,29.0,18.0,18.0,Clinic/Physician Referral,Elective,2022-04-29 18:20:00,...,0,1,0,626973.0,20177,39.053098,-95.720976,890.0,177,Shawnee
2,01/10/22,2022-01-10 05:52:00,2022.0,1.0,10.0,5.0,52.0,Non-Health Care Facility Point of Origin,Elective,2022-01-12 11:43:00,...,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,03/08/22,2022-03-08 09:08:00,2022.0,3.0,8.0,9.0,8.0,Non-Health Care Facility Point of Origin,Elective,2022-03-10 13:45:00,...,1,0,0,385246.0,20177,39.023433,-95.660754,1687.0,177,Shawnee
4,03/16/22,2022-03-16 14:19:00,2022.0,3.0,16.0,14.0,19.0,Non-Health Care Facility Point of Origin,Elective,2022-03-16 16:00:00,...,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN