# Initial Data Observations

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
departments = pd.read_csv("departments.csv")
diagnosis = pd.read_csv("diagnosis.csv")
encounters = pd.read_csv("encounters.csv")
patients = pd.read_csv("patients.csv")
providers = pd.read_csv("providers.csv")
social_determinants = pd.read_csv("social_determinants.csv")
tiger_census_codes = pd.read_csv("tigercensuscodes.csv")

/var/folders/5z/2qf3kgpn4s1268wng8ysvpl00000gq/T/ipykernel_9866/1600531716.py:6: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  social_determinants = pd.read_csv("social_determinants.csv")

In [4]:
departments

,DepartmentKey,Address,City,County,DepartmentName,DepartmentSpecialty,DepartmentType,PostalCode,CensusTract
0,-3,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,NaN
1,-2,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,NaN
2,-1,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,NaN
3,1,1500 SW 10th ST,TOPEKA,*Unspecified,INITIAL DEPT,*Unspecified,*Unknown,66604,2.017700e+10
4,2,1979 Milky Way,VERONA,*Unspecified,EHS UM DEPT,*Unspecified,*Unknown,53593,5.502501e+10
...,...,...,...,...,...,...,...,...,...
11592,12908,909 SW Mulvane St,TOPEKA,SHAWNEE,STORMONT VAIL ALLERGY CLINIC,Allergy,*Unknown,66606,2.017700e+10
11593,12909,1414 SW 8th Ave,Topeka,*Unspecified,CC HEMATOLOGY ONCOLOGY,Hematology and Oncology,*Unknown,66606,2.017700e+10
11594,12910,NaN,NaN,*Unspecified,*Unspecified,*Unspecified,*Unspecified,NaN,NaN
11595,12911,1500 SW 10th Ave,Topeka,SHAWNEE,SV PHARMACOTHERAPY,Pharmacy,HOD,66606,2.017700e+10
11596,12912,330 SW Oakley,TOPEKA,SHAWNEE,ASTRA MENTAL HEALTH & RECOVERY,*Not Applicable,*Not Applicable,66606,2.017700e+10

In [5]:
diagnosis

,DiagnosisKey,GroupName,GroupCode,DiagnosisName,DiagnosisValue
0,2.0,Typhoid and paratyphoid fevers,ICD-10-CM: A01,"Paratyphoid fever, unspecified( ICD-10-CM: A01...",A01.4
1,3.0,Respiratory tuberculosis,ICD-10-CM: A15,Primary respiratory tuberculosis( ICD-10-CM: A...,A15.7
2,7.0,Fracture at wrist and hand level,ICD-10-CM: S62,"Displaced fracture of pisiform, unspecified wr...",S62.163K
3,8.0,Fracture of rib,ICD-10-CM: S22,"Multiple fractures of ribs, right side, subseq...",S22.41XG
4,9.0,Fracture at wrist and hand level,ICD-10-CM: S62,Nondisplaced fracture of distal phalanx of lef...,S62.663G
...,...,...,...,...,...
1531257,1629328.0,Reserved for inherently not codable concepts w...,ICD-10-CM: IMO0001,Reserved for inherently not codable concepts w...,IMO0001
1531258,1629331.0,Reserved for concepts with insufficient inform...,ICD-10-CM: IMO0002,Reserved for concepts with insufficient inform...,IMO0002
1531259,1629340.0,Reserved for concepts with insufficient inform...,ICD-10-CM: IMO0002,Reserved for concepts with insufficient inform...,IMO0002
1531260,1629341.0,Reserved for concepts with insufficient inform...,ICD-10-CM: IMO0002,Reserved for concepts with insufficient inform...,IMO0002
1531261,1629359.0,Abdominal and pelvic pain,ICD-10-CM: R10,Pelvic and perineal pain bilateral( ICD-10-CM:...,R10.23

In [6]:
encounters

,Date,AdmissionInstant,AdmitYear,AdmitMonth,AdmitDay,AdmitHour,AdmitMinute,AdmissionSource,AdmissionType,DischargeInstant,...,AttendingProviderDurableKey,DischargeProviderDurableKey,DepartmentKey,PrimaryDiagnosisKey,IsEdVisit,IsHospitalAdmission,IsHospitalOutpatientVisit,IsInpatientAdmission,IsObservation,IsOutpatientFaceToFaceVisit
0,04/25/22,2022-04-25 20:33:00,2022.0,4.0,25.0,20.0,33.0,Non-Health Care Facility Point of Origin,Elective,2022-04-25 21:35:00,...,2982,2982,27,910699,0,1,0,0,1,0
1,04/29/22,2022-04-29 18:18:00,2022.0,4.0,29.0,18.0,18.0,Clinic/Physician Referral,Elective,2022-04-29 18:20:00,...,2979,2979,27,-1,0,1,0,0,1,0
2,01/10/22,2022-01-10 05:52:00,2022.0,1.0,10.0,5.0,52.0,Non-Health Care Facility Point of Origin,Elective,2022-01-12 11:43:00,...,6223,7015,27,468738,0,1,0,1,0,0
3,03/08/22,2022-03-08 09:08:00,2022.0,3.0,8.0,9.0,8.0,Non-Health Care Facility Point of Origin,Elective,2022-03-10 13:45:00,...,7973,7973,27,468492,0,1,0,1,0,0
4,03/16/22,2022-03-16 14:19:00,2022.0,3.0,16.0,14.0,19.0,Non-Health Care Facility Point of Origin,Elective,2022-03-16 16:00:00,...,6223,2982,27,907210,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7675796,12/29/25,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,18326,-1,57,858635,0,0,0,0,0,1
7675797,12/12/25,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,-1,-1,12707,-1,0,0,0,0,0,1
7675798,12/12/25,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,79382,-1,57,855970,0,0,0,0,0,1
7675799,08/20/25,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,1868,-1,11805,853446,0,0,0,0,0,0
7675800,07/17/25,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,1868,-1,11805,853446,0,0,0,0,0,0

In [7]:
encounters.isnull().sum()

Date                                 0
AdmissionInstant               6627001
AdmitYear                      6627001
AdmitMonth                     6627001
AdmitDay                       6627001
AdmitHour                      6627001
AdmitMinute                    6627001
AdmissionSource                   1400
AdmissionType                     1086
DischargeInstant               6627001
DischargeYear                  6627001
DischargeMonth                 6627001
DischargeDay                   6627001
DischargeHour                  6627001
DischargeMinute                6627001
EncounterKey                         0
PatientDurableKey                    0
Type                                 0
VisitType                            0
VisitTypeDescription                 0
ProviderDurableKey                   0
AttendingProviderDurableKey          0
DischargeProviderDurableKey          0
DepartmentKey                        0
PrimaryDiagnosisKey                  0
IsEdVisit                            0
IsHospitalAdmission                  0
IsHospitalOutpatientVisit            0
IsInpatientAdmission                 0
IsObservation                        0
IsOutpatientFaceToFaceVisit          0
dtype: int64

In [9]:
1531262/7675801

0.19949214420749053

In [10]:
encounters_null = encounters.loc[encounters["DischargeYear"].isnull()]
encounters_null

,Date,AdmissionInstant,AdmitYear,AdmitMonth,AdmitDay,AdmitHour,AdmitMinute,AdmissionSource,AdmissionType,DischargeInstant,...,AttendingProviderDurableKey,DischargeProviderDurableKey,DepartmentKey,PrimaryDiagnosisKey,IsEdVisit,IsHospitalAdmission,IsHospitalOutpatientVisit,IsInpatientAdmission,IsObservation,IsOutpatientFaceToFaceVisit
8,01/03/22,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,-1,-1,10279,793876,0,0,0,0,0,1
9,01/31/22,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,-1,-1,10279,694326,0,0,0,0,0,1
10,01/31/22,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,-1,-1,10279,686369,0,0,0,0,0,1
11,01/24/22,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,-1,-1,349,847384,0,0,0,0,0,1
12,01/26/22,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,-1,-1,10279,1016440,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7675796,12/29/25,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,18326,-1,57,858635,0,0,0,0,0,1
7675797,12/12/25,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,-1,-1,12707,-1,0,0,0,0,0,1
7675798,12/12/25,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,79382,-1,57,855970,0,0,0,0,0,1
7675799,08/20/25,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,1868,-1,11805,853446,0,0,0,0,0,0
7675800,07/17/25,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,1868,-1,11805,853446,0,0,0,0,0,0

In [11]:
encounters_null.isnull().sum()

Date                                 0
AdmissionInstant               6627001
AdmitYear                      6627001
AdmitMonth                     6627001
AdmitDay                       6627001
AdmitHour                      6627001
AdmitMinute                    6627001
AdmissionSource                      1
AdmissionType                        1
DischargeInstant               6627001
DischargeYear                  6627001
DischargeMonth                 6627001
DischargeDay                   6627001
DischargeHour                  6627001
DischargeMinute                6627001
EncounterKey                         0
PatientDurableKey                    0
Type                                 0
VisitType                            0
VisitTypeDescription                 0
ProviderDurableKey                   0
AttendingProviderDurableKey          0
DischargeProviderDurableKey          0
DepartmentKey                        0
PrimaryDiagnosisKey                  0
IsEdVisit                            0
IsHospitalAdmission                  0
IsHospitalOutpatientVisit            0
IsInpatientAdmission                 0
IsObservation                        0
IsOutpatientFaceToFaceVisit          0
dtype: int64

In [13]:
encounters_null["VisitType"].value_counts()

VisitType
LAB                                 1114143
FOLLOW UP                            980175
*Unspecified                         848133
X-RAY VT                             346126
OFFICE VISIT                         291575
                                     ...
EGD/FLEX SIG-MSH                          1
OAKLAND COMM CTR HOSP/FU                  1
MRI ANGIO ABDOMEN WO CONTRAST VT          1
ENDO/IUD                                  1
US FHC OB/GYN ULTRASOUND VT               1
Name: count, Length: 1073, dtype: int64

In [14]:
encounters_not_null = encounters.loc[~encounters["DischargeYear"].isnull()]
encounters_not_null

,Date,AdmissionInstant,AdmitYear,AdmitMonth,AdmitDay,AdmitHour,AdmitMinute,AdmissionSource,AdmissionType,DischargeInstant,...,AttendingProviderDurableKey,DischargeProviderDurableKey,DepartmentKey,PrimaryDiagnosisKey,IsEdVisit,IsHospitalAdmission,IsHospitalOutpatientVisit,IsInpatientAdmission,IsObservation,IsOutpatientFaceToFaceVisit
0,04/25/22,2022-04-25 20:33:00,2022.0,4.0,25.0,20.0,33.0,Non-Health Care Facility Point of Origin,Elective,2022-04-25 21:35:00,...,2982,2982,27,910699,0,1,0,0,1,0
1,04/29/22,2022-04-29 18:18:00,2022.0,4.0,29.0,18.0,18.0,Clinic/Physician Referral,Elective,2022-04-29 18:20:00,...,2979,2979,27,-1,0,1,0,0,1,0
2,01/10/22,2022-01-10 05:52:00,2022.0,1.0,10.0,5.0,52.0,Non-Health Care Facility Point of Origin,Elective,2022-01-12 11:43:00,...,6223,7015,27,468738,0,1,0,1,0,0
3,03/08/22,2022-03-08 09:08:00,2022.0,3.0,8.0,9.0,8.0,Non-Health Care Facility Point of Origin,Elective,2022-03-10 13:45:00,...,7973,7973,27,468492,0,1,0,1,0,0
4,03/16/22,2022-03-16 14:19:00,2022.0,3.0,16.0,14.0,19.0,Non-Health Care Facility Point of Origin,Elective,2022-03-16 16:00:00,...,6223,2982,27,907210,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7674805,12/31/25,2025-12-31 22:16:00,2025.0,12.0,31.0,22.0,16.0,Non-Health Care Facility Point of Origin,Emergency,2025-12-31 22:27:00,...,73372,73372,11788,865125,1,0,0,0,0,0
7674834,12/31/25,2025-12-31 19:31:00,2025.0,12.0,31.0,19.0,31.0,Non-Health Care Facility Point of Origin,Emergency,2025-12-31 19:36:00,...,6561,-1,20,855088,1,0,0,0,0,0
7674847,12/31/25,2025-12-31 15:56:00,2025.0,12.0,31.0,15.0,56.0,Non-Health Care Facility Point of Origin,Emergency,2025-12-31 15:57:00,...,26866,26866,20,864701,1,0,0,0,0,0
7674886,12/31/25,2025-12-31 10:49:00,2025.0,12.0,31.0,10.0,49.0,Non-Health Care Facility Point of Origin,Emergency,2025-12-31 10:50:00,...,6561,-1,20,915009,1,0,0,0,0,0
7675288,12/31/25,2025-12-31 23:59:00,2025.0,12.0,31.0,23.0,59.0,Clinic/Physician Referral,Elective,2025-12-31 23:59:00,...,1238,-1,44,-1,0,0,1,0,0,1

In [15]:
encounters_not_null["VisitType"].value_counts()

VisitType
*Unspecified                              365693
RXT10                                      42205
CR PHASE 2                                 34002
FL FLUORO GUIDE SPINAL PUNCTURE OP VT      28820
ECHOCARDIOGRAM ADULT                       27493
                                           ...
CT LUMBAR SPINE W CONTRAST AFTER NM VT         1
MRI NEUROGRAPHY VT ANESTHESIA VT               1
CT CHEST W WO CONTRAST HVT                     1
US DUPLEX ABDOMEN VASCULAR LIMITED VT          1
LEQVIO INJECTION                               1
Name: count, Length: 1056, dtype: int64

In [16]:
encounters_null["Type"].value_counts()

Type
Office Visit                2249136
Lab Visit                   1052018
Appointment                  778962
Patient Outreach             555223
Imaging                      526382
Treatment                    325547
Lab Requisition              202048
Follow-Up                    156964
Initial consult              142248
Procedure visit              130701
Telemedicine                 117123
Well Child                   110177
Surgery                       72851
Anti-coag visit               66814
Routine Prenatal              63820
Infusion                      55337
Pre-Endoscopy Assessment      21650
Name: count, dtype: int64

In [17]:
encounters_not_null["Type"].value_counts()

Type
Hospital Encounter    1048800
Name: count, dtype: int64